swipe:
  3: 
    left: 
      sendkey: 'LEFTALT+RIGHT'
    right: 
      sendkey: 'LEFTALT+LEFT'
      
  4:
    left: 
      sendkey: 'LEFTCTRL+LEFTMETA+RIGHT'
    right: 
      sendkey: 'LEFTCTRL+LEFTMETA+LEFT'
