GRAY="#808080"
BLUE="#569CD6"
DARK_BLUE="#223E55"
RED="#EE4646"
YELLOW="#CCCC99"
BACKGROUND="#000000"
FOREGROUND="#CCCCCC"

set -g status-interval 1
set -g status-style bg=$BACKGROUND,fg=$BLUE

set -g pane-border-style fg=$DARK_BLUE
set -g pane-active-border-style fg=$BLUE

set -g status-left " "

set -g window-status-current-format "#[fg=$BLUE]#I #W"
set -g window-status-format "#[fg=$GRAY]#I #W"
set -g window-status-activity-style fg=$RED
set -g window-status-bell-style fg=$YELLOW
set -g window-status-separator "#[fg=$GRAY] | "
set -g window-style default
set -g window-status-style bg=$BACKGROUND,fg=$GRAY
set -g window-status-current-style "underscore"

set -g status-right-length 150
set -g status-right "#T %Y-%m-%d %H:%M:%S "

set -g mouse on

# Keys to toggle monitoring activity in a window and the synchronize-panes option
bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'
